spring.datasource.url=jdbc:postgresql://localhost:5432/pesagem
spring.datasource.username=pesagem
spring.datasource.password=pesagem

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.show-sql=true

spring.flyway.repair-on-migrate=false
spring.flyway.validate-on-migrate=false

logging.level.com.pesagem_graos_app.scheduler=WARN

estabilizacao.janela-minima=5
estabilizacao.threshold-kg=0.5

spring.task.scheduling.enabled=true

