spring.datasource.url=jdbc:postgresql://localhost:5432/pesagem
spring.datasource.username=pesagem
spring.datasource.password=pesagem

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.show-sql=true

spring.flyway.repair-on-migrate=false
spring.flyway.validate-on-migrate=false